### ISSUE TITLE
Can't send string as body

### ISSUE THREAD

**Issue by pkonneker** [geoffdutton/lambda-proxy-utils#1]
If I try to response.send("a string"), the library will throw a json parse error.

**Comment by geoffdutton** [comment]
Hmm, so I have this test for sending a string: https://github.com/geoffdutton/lambda-proxy-utils/blob/master/test/events/response.test.js#L168

I wonder if there's some other pieces of the request that throw the JSON parse error? Do you have more context around when calling `response.send("a string")` throws a parse error?

**Comment by pkonneker** [comment]
Okay, issue is in user's brain. JSON.parse will fail unless you include " or ' in the string indicating that you are in fact sending a string as json.

Makes sense.

Thanks for your help!
